IdGen-master/idapp/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

import views

urlpatterns = [url(r'^$',views.mainpage,name='Main'),
				url(r'^studentHome$',views.studentHome,name='studentHome'),
				url(r'^facultyHome$',views.facultyHome,name='facultyHome'),
				url(r'^studentRegistration/$',views.studentRegistration,name='studentRegistration'),
				url(r'^facultyRegistration/$',views.facultyRegistration,name='facultyRegistration'),
				url(r'^studentPdf/$',views.studentPdf,name='studentPdf'),
				url(r'^studentListSave/$',views.studentListSave,name='studentListSave'),
				url(r'^studentSave/$',views.studentSave,name='studentSave'),
				url(r'^facultySave/$',views.facultySave,name='facultySave'),
				url(r'^studentDelete/$',views.studentDelete,name='studentDelete'),
				url(r'^facultyDelete/$',views.facultyDelete,name='facultyDelete'),
				url(r'^studentTemplateInput/$', views.studentTemplateInput, name='studentTemplateInput'),
				url(r'^studentTemplate/$', views.studentTemplate, name='studentTemplate'),
				url(r'^facultyTemplateInput/$', views.facultyTemplateInput, name='facultyTemplateInput'),
				url(r'^facultyTemplate/$', views.facultyTemplate, name='facultyTemplate'),
				url(r'^studentPdfPreview/$', views.studentPdfPreview, name='studentPdfPreview'),
				url(r'^facultyPdfPreview/$', views.facultyPdfPreview, name='facultyPdfPreview'),
				url(r'^facultyPdf/$',views.facultyPdf,name='facultyPdf'),
				url(r'^studentList/$',views.studentList,name='studentList'),
				url(r'^facultyList/$',views.facultyList,name='facultyList'),
				url(r'^login/$',views.login1,name='login'),
				url(r'^logout/$',views.logout1,name='logout'),
				url(r'^singleStudent/$',views.singleStudent,name='singleStudent'),
				url(r'^studentEdit/(?P<id>\d+)/$',views.studentEdit,name='studentEdit'),
				url(r'^facultyEdit/(?P<id>\d+)/$',views.facultyEdit,name='facultyEdit'),
				url(r'^studentPdfHome/$',views.studentPdfHome,name='studentPdfHome'),
				url(r'^report/$',views.report,name='report'),
				
				]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

IdGen-master/idcard/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from idapp import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('idapp.urls')),
]

#if settings.DEBUG:
 #  urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

IdGen-master/idapp/models.py
from __future__ import unicode_literals

from django.db import models

class student(models.Model):
  name=models.CharField(max_length=200)
  course=models.CharField(max_length=200)
  branch=models.CharField(max_length=200)
  typ = models.CharField(max_length=10)
  admissionNumber=models.CharField(max_length=200,unique=True)
  validtill=models.DateField()
  dateofbirth=models.DateField()
  bloodgroup=models.CharField(max_length=200,blank=True,null=True)
  address=models.CharField(max_length=200)
  contact1=models.CharField(max_length=10)
  contact2=models.CharField(max_length=10,blank=True,null=True)
  photo=models.ImageField(upload_to="student",blank=True,null=True)
  clss=models.CharField(max_length=5,blank=True,null=True)
  rollno=models.CharField(max_length=5,blank=True,null=True)
  barcode_serial=models.CharField(max_length=200,unique=True,null=True)
  
  def __str__(self):
    return self.name

class faculty(models.Model):
  name=models.CharField(max_length=200)
  designation=models.CharField(max_length=200)
  dateofbirth=models.DateField()
  bloodgroup=models.CharField(max_length=200)
  address=models.CharField(max_length=200)
  contact=models.CharField(max_length=10)
  photo=models.ImageField(upload_to="faculty")
  barcode_serial=models.CharField(max_length=200,unique=True)
  
  def __str__(self):
     return self.name

class studentTemplateDesign(models.Model):
  collegeName = models.CharField(max_length=120)
  collegeNameFont = models.CharField(max_length=120)
  collegeNameFontSize = models.IntegerField()
  addressLine1 = models.CharField(max_length=120)
  addressLine2 = models.CharField(max_length=120)
  addressLine3 = models.CharField(max_length=120)
  addressLine4 = models.CharField(max_length=120)
  addressLine5 = models.CharField(max_length=120)
  addressLine1To5Font = models.CharField(max_length=120)
  addressLine1To5FontSize = models.IntegerField()
  detailsFont = models.CharField(max_length=120)
  detailsFontSize = models.IntegerField()
  collegeLogo = models.ImageField(upload_to="template_student", null=True, blank=True)
  parentLogo = models.ImageField(upload_to="template_student", null=True, blank=True)
  principalSign = models.ImageField(upload_to="template_student", null=True, blank=True)
  backgroundDesign = models.ImageField(upload_to="template_student", null=True, blank=True)
  
  def __unicode__(self):
    return self.collegeName
  def __str__(self):
    return self.collegeName

class facultyTemplateDesign(models.Model):
  collegeName = models.CharField(max_length=120)
  collegeNameFont = models.CharField(max_length=120)
  collegeNameFontSize = models.IntegerField()
  addressLine1 = models.CharField(max_length=120)
  addline1font = models.CharField(max_length=120)
  addline1fontsize = models.IntegerField()
  addressLine2 = models.CharField(max_length=120)
  addressLine3 = models.CharField(max_length=120)
  addressLine4 = models.CharField(max_length=120)
  addressLine5 = models.CharField(max_length=120)
  addressLine2To5Font = models.CharField(max_length=120)
  addressLine2To5FontSize = models.IntegerField()
  detailsFont = models.CharField(max_length=120)
  detailsFontSize = models.IntegerField()
  parentLogo = models.ImageField(upload_to="template_faculty", null=True, blank=True)
  principalSign = models.ImageField(upload_to="template_faculty", null=True, blank=True)
  backgroundDesign = models.ImageField(upload_to="template_faculty", null=True, blank=True)
  
  def __unicode__(self):
    return self.collegeName
  def __str__(self):
    return self.collegeName

IdGen-master/idapp/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse,HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
# imports for reportlab pdfgeneration
from reportlab.graphics.barcode import code128
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from .forms import StudentForm,FacultyForm,StudentTemplateForm, FacultyTemplateForm,SingleStudentForm
from .models import student,faculty,studentTemplateDesign, facultyTemplateDesign
import os
import re
import zipfile

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def login1(request):
  next=request.GET.get('next','/')
  if request.method=="POST":
    username=request.POST['username']
    password=request.POST['password']
    user=authenticate(username=username,password=password)
    if user is not None:
      if user.is_active:
        login(request,user)
        return HttpResponseRedirect('/')
      else:
        HttpResponse("Inactive user!")
    else:
      return HttpResponseRedirect('/login/')
  return render(request,"login.html",{'redirect_to':next})


def logout1(request):
  logout(request)
  return HttpResponseRedirect('/')


def mainpage(request):
   return render(request,'home.html')

@login_required(login_url='/login/')
def studentHome(request):
   return render(request,'studentHome.html')

@login_required(login_url='/login/')
def facultyHome(request):
   return render(request,'facultyHome.html')

@login_required(login_url='/login/')
def studentRegistration(request):
	if request.method=='POST':
		try:
			a=student.objects.get(admissionNumber=request.POST.get("admissionNumber"))
		except:
			form=StudentForm(request.POST,request.FILES)
			if form.is_valid():
				instance=form.save(commit=False)
				instance.save()
				messages.success(request, 'Student Registered Succesfully.')
				return HttpResponseRedirect('/studentRegistration')
			else:
				form=StudentForm()
				context={"form":form}
				messages.error(request, 'Form Not Valid.')
				return render(request,'studentRegistration.html',context)
		else:
			form=StudentForm()
			context={"form":form}
			messages.error(request, 'Student Exists.')
			return render(request,'studentRegistration.html',context)
	else:
		form=StudentForm()
		context={"form":form}
		return render(request,'studentRegistration.html',context)

@login_required(login_url='/login/')
def facultyRegistration(request):
   if request.method=='POST':
    try:
      a=faculty.objects.get(barcode_serial=request.POST.get("barcode_serial"))
    except:
     form=FacultyForm(request.POST,request.FILES)
     if form.is_valid():
       instance=form.save(commit=False)
       instance.save()
       messages.success(request, 'Faculty Registered Succesfully.')
       return HttpResponseRedirect('/facultyRegistration') 
     else:
       form=FacultyForm()
       context={"form":form}
       messages.error(request, 'Form Not Valid.')
       return render(request,'facultyRegistration.html',context)
    else:
    	form=FacultyForm()
    	context={"form":form}
    	messages.error(request, 'Faculty Exists.')
    	return render(request,'facultyRegistration.html',context)
   else:
     #errormsg="Method not POST"
     form=FacultyForm()
     context={"form":form}
     return render(request,'facultyRegistration.html',context)


@login_required(login_url='/login/')
def studentEdit(request, id=None):
  instance = get_object_or_404(student, id=id)
  form=StudentForm(request.POST or None,request.FILES or None, instance=instance)
  if form.is_valid():
        instance=form.save(commit=False)
        instance.save()
  context = {
  	"instance":instance,
  	"form":form,
  	"name":instance.name,
  }
  return render(request,'studentEditForm.html',context)

@login_required(login_url='/login/')
def facultyEdit(request, id=None):
	instance = get_object_or_404(faculty, id=id)
	form=FacultyForm(request.POST or None,request.FILES or None, instance=instance)
	if form.is_valid():
		instance=form.save(commit=False)
		instance.save()
	context = {
		"instance":instance,
		"form":form,
		"name":instance.name,
	}
	return render(request,'facultyEditForm.html',context)

@login_required(login_url='/login/')
def studentPdfHome(request):
	return render(request,'studentPdfHome.html')

@login_required(login_url='/login/')
def studentPdf(request):
	details=studentTemplateDesign.objects.all()
	if not len(details):
		return HttpResponseRedirect('/studentTemplateInput')
	details=studentTemplateDesign.objects.get()
	if request.method=="POST":
		try:
			smallest=100000000
			largest=0
			for i in student.objects.all():
			    a=int(i.admissionNumber.split('/')[0])
			    if a<smallest:
			    	smallest=a
			    	#print smallest
			    elif a>largest:
		      		largest=a
		      		#print largest
			a=int(request.POST['range'].split('-')[0])
			b=int(request.POST['range'].split('-')[1])
			q=[]
			if(a<smallest):
				a=smallest
				#print smallest
			elif(b>largest):
				b=largest
				#print largest
			for i in student.objects.all():
				if((int(i.admissionNumber.split('/')[0])>=a)and(int(i.admissionNumber.split('/')[0])<=b)):
					q.append(i)

			if q.__len__()==0:
			  	return render(request,'home.html')
			details=studentTemplateDesign.objects.get()
			back = root + '/media/'+ str(details.backgroundDesign)
			princi = root + '/media/'+ str(details.principalSign)
			logoright = root + '/media/'+ str(details.parentLogo)
			logoleft = root + '/media/'+ str(details.collegeLogo)
			width = 540*mm
			height = 860*mm
			c = canvas.Canvas("pdf/"+'rangefront.pdf')
			for i in q:
			  pic = root + i.photo.url
			  c.setPageSize((width, height))
			  if details.backgroundDesign:
			    c.drawImage(back, 0, 0, height=height, width=width)
			#c.saveState()
			  if details.collegeLogo:
			    c.drawImage(logoleft, 20*mm, 740*mm, height=80*mm, width=80*mm)
			  if details.parentLogo:
			    c.drawImage(logoright, 450*mm, 740*mm, height=80*mm, width=80*mm)
			  c.setFont(str(details.collegeNameFont), int(details.collegeNameFontSize))
			  c.drawCentredString(width/2, height-(60*mm),str(details.collegeName))
			  c.setFont(str(details.addressLine1To5Font), int(details.addressLine1To5FontSize))
			  c.drawCentredString(width/2, height-(80*mm),str(details.addressLine1))
			  c.setFont(str(details.addressLine1To5Font), int(details.addressLine1To5FontSize))
			  c.drawCentredString(width/2, height-(100*mm), str(details.addressLine2))
			  #c.drawCentredString(width/2, height-(120*mm), "")  Kerala, India, PIN: 682 021 
			  c.drawCentredString(width/2, height-(120*mm),str(details.addressLine3))
			  c.drawCentredString(width/2, height-(140*mm),str(details.addressLine4))
			  c.setFont(str(details.addressLine1To5Font), int(details.addressLine1To5FontSize))
			  c.drawCentredString(width/2, height-(160*mm), str(details.addressLine5))
			  if i.photo.url:
			  	c.drawImage(pic, 170*mm, height-(375*mm), height=200*mm, width=200*mm)
			  c.setFont(str(details.detailsFont), int(details.detailsFontSize))
			  c.drawString(30*mm, 430*mm, "Name :")
			  c.drawString(165*mm, 430*mm,i.name)
			  c.setFont(str(details.detailsFont), int(details.detailsFontSize))
			  c.drawString(30*mm, 340*mm, "Course :")
			  c.drawString(165*mm, 340*mm,i.course)
			  c.drawString(30*mm, 280*mm, "Branch :")
			  c.drawString(165*mm, 280*mm, i.branch)
			  c.drawString(30*mm, 180*mm, "ADMN No :")
			  c.drawString(165*mm, 180*mm, i.admissionNumber)
			  c.drawString(30*mm, 120*mm, "Valid Till :")
			  c.drawString(165*mm, 120*mm,str(i.validtill.day)+'/'+str(i.validtill.month)+'/'+str(i.validtill.year))
			  c.drawString(30*mm, 60*mm, "Date Of Birth:")
			  c.drawString(165*mm, 60*mm,str(i.dateofbirth.day)+'/'+str(i.dateofbirth.month)+'/'+str(i.dateofbirth.year))
			  c.setFont('Times-Bold', 60)
			  c.drawString(420*mm, 20*mm, "Principal")
			  if details.principalSign:
			    c.drawImage(princi, 420*mm, 45*mm, height= 50*mm, width=80*mm)
			  c.showPage()
			c.save()
			c = canvas.Canvas("pdf/"+'rangeback.pdf')
			for i in q:
			  barcode128 = code128.Code128(i.barcode_serial, barHeight=50*mm, barWidth=1.5*mm)
			  c.setPageSize((width, height))
			  c.setFont(str(details.detailsFont), int(details.detailsFontSize))
			  barcode128.drawOn(c, 130*mm, 750*mm)
			  c.drawString(190*mm, 720*mm, i.barcode_serial)
			  c.drawString(30*mm, 630*mm, "Blood Group :")
			  c.drawString(210*mm, 630*mm,i.bloodgroup)
			  c.drawString(30*mm, 550*mm, "Address :")
			  le=i.address.__len__()
			  n=0
			      #x=2
			  ht=550
			  y=re.split(',',i.address)
			  y=re.split(',',i.address)
			  for x in y:
			    c.drawString(210*mm, ht*mm,x)
			    ht=ht-40

			  c.drawString(30*mm, 170*mm, "Contact No. :")
			  c.drawString(210*mm, 170*mm,i.contact1)
			  c.drawString(210*mm, 140*mm,i.contact2)
			  c.drawString(30*mm, 60*mm, "Signature     :")
			  c.rect(160*mm,30*mm,320*mm,70*mm)
			  c.showPage()
			c.save()

			arch=zipfile.ZipFile("pdf/"+"range.zip","w")
			arch.write("pdf/"+'rangefront.pdf')
			arch.write("pdf/"+'rangeback.pdf')
			arch.close()
			response = HttpResponse(open(root+"/pdf"+'/range.zip', 'rb').read(), content_type='application/zip')
			response['Content-Disposition'] = 'attachment; filename=range.zip'
			return response
			return render(request,'home.html')				
		except:
			messages.error(request, 'Please Fill Details of' + i.name)
			return HttpResponseRedirect('/studentList')
	else:
		try:
			q=student.objects.all()
			if q.__len__()==0:
				return render(request,'home.html')
			details=studentTemplateDesign.objects.get()
			back = root + '/media/'+ str(details.backgroundDesign)
			princi = root + '/media/'+ str(details.principalSign)
			logoright = root + '/media/'+ str(details.parentLogo)

IdGen-master/idapp/templates/base.html
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">IdGen</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Student<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{%url 'studentRegistration' %}">Registration</a></li>
                <li><a href="{%url 'studentList' %}">List</a></li>
                <li><a href="{%url 'studentTemplateInput' %}">Template</a></li>
                <li><a href="{%url 'studentPdfHome' %}">Generate Pdf</a></li>
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Faculty<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{%url 'facultyRegistration' %}">Registration</a></li>
                <li><a href="{%url 'facultyList' %}">List</a></li>
                <li><a href="{%url 'facultyTemplateInput' %}">Template</a></li>
                <li><a href="{%url 'facultyPdf' %}">Generate Pdf</a></li>
              </ul>
            </li>
          </ul>
          {% if user.is_authenticated %}
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{%url 'logout' %}">Logout</a></li>
            </ul>
          {% endif %}
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    {% block content %}
	  {% endblock %}

IdGen-master/idapp/templates/facultyHome.html
<htmL>
	<head>
		<title>Faculty Page</title>
		<style type="text/css">
		div {
			width: 200px;
		}

		h2 {
			font: 400 40px/1.5 Helvetica, Verdana, sans-serif;
			margin: 0;
			padding: 0;
		}

		ul {
			list-style-type: none;
			margin: 0;
			padding: 0;
		}

		li {
			font: 200 20px/1.5 Helvetica, Verdana, sans-serif;
			border-bottom: 1px solid #ccc;
		}

		li:last-child {
			border: none;
		}

		li a {
			text-decoration: none;
			color: #000;
			display: block;
			width: 200px;

			-webkit-transition: font-size 0.3s ease, background-color 0.3s ease;
			-moz-transition: font-size 0.3s ease, background-color 0.3s ease;
			-o-transition: font-size 0.3s ease, background-color 0.3s ease;
			-ms-transition: font-size 0.3s ease, background-color 0.3s ease;
			transition: font-size 0.3s ease, background-color 0.3s ease;
		}

		li a:hover {
			font-size: 25px;
			background: #f6f6f6;
		}
		</style>
	</head>
	<body>
		<div>
			<h2>Faculty</h2><br>
			<ul>
				<li><a href="{%url 'facultyRegistration' %}">FACULTY-REGISTRATION</a></li>
				<li><a href="{%url 'facultyList' %}">FACULTY LIST / EDIT</a></li>
				<li><a href="{%url 'facultyTemplateInput' %}">FACULTY TEMPLATE SET</a></li>
				<li><a href="{%url 'facultyPdf' %}">FACULTY PDF GENERATION</a></li>
				<li><a href="{%url 'Main' %}">HOME</a></li>
			</ul>
		</div>
	</body>
	</html>

IdGen-master/idapp/templates/facultyRegistration.html
<!DOCTYPE html>
<html>
<head>
  <title>Student Registration</title>
  <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7; IE=EmulateIE9">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <link href='https://fonts.googleapis.com/css?family=Fira+Sans' rel='stylesheet' type='text/css'>
  <link href="/static/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="/static/css/demo.css" media="all" />
  <link rel="stylesheet" type="text/css" href="/static/css/style.css" media="all" />

</head>

<body>
  {% extends "base.html" %}

  {% block content %}
  {% if messages %}
      {% for message in messages %}
        {% if message.tags == "success" %}
          <div class="alert alert-success fade in text-center">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {{ message }}
          </div>
        {% else %}
           <div class="alert alert-danger fade in text-center">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {{ message }}
          </div>
        {% endif %}
      {% endfor %}
  {% endif %}
  <div class="cont">
   <header>
    <h1 class="head">Faculty Registration</h1>
  </header>       
  <div  class="form" >
  	{{ form.non_field_errors }}
    <form id="contactform" action="{% url 'facultyRegistration' %}" enctype="multipart/form-data" method="post">{% csrf_token %}
     <p class="contact"><label for="{{form.name.id_for_label}}">Name*</label></p> 
     <input id="id_name" maxlength="200" name="name" type="text" required="" />

     <p class="contact"><label for="{{form.designation.id_for_label}}">Designation*</label></p> 
     <input id="id_designation" maxlength="200" name="designation" type="text" required="" />
  
     <fieldset><label for="{{form.dateofbirth.id_for_label}}">Date of Birth* &nbsp </label>
     {{form.dateofbirth}}</fieldset>

      <p class="contact"><label for="{{form.bloodgroup.id_for_label}}">Blood Group*</label></p> 
       <input id="id_bloodgroup" maxlength="200" name="bloodgroup" type="text" required="" />
     
      <p class="contact"><label for="{{form.address.id_for_label}}">Address*</label></p> 
      <input id="id_address" maxlength="200" name="address" type="text" required="" />

      <p class="contact"><label for="{{form.contact.id_for_label}}">Contact No.*</label></p> 
      <input id="id_contact" maxlength="10" name="contact" type="text" required="" />  <br>

      <p class="contact"><label for="{{form.barcode_serial.id_for_label}}">Barcode Serial*</label></p> 
      <input id="id_barcode_serial" maxlength="10" name="barcode_serial" type="text" required="" /><br>

      <p class="contact"><label for="{{form.photo.id_for_label}}">Photo*</label></p> 
      <input id="id_photo" name="photo" type="file" required="" /><br>

      <input class="buttom" name="submit" id="submit" value="Register" type="submit">    
    </form> 
  </div>      
</div>

<script src="/static/js/jquery.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
</body>

</html>

{% endblock %}

IdGen-master/idapp/templates/studentRegistration.html
<!DOCTYPE html>
<html>
<head>
  <title>Student Registration</title>
  <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7; IE=EmulateIE9">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
  <link href='https://fonts.googleapis.com/css?family=Fira+Sans' rel='stylesheet' type='text/css'>
  <link href="/static/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="/static/css/demo.css" media="all" />
  <link rel="stylesheet" type="text/css" href="/static/css/style.css" media="all" />

</head>

<body>
  {% extends "base.html" %}

  {% block content %}
  {% if messages %}
      {% for message in messages %}
        {% if message.tags == "success" %}
          <div class="alert alert-success fade in text-center">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {{ message }}
          </div>
        {% else %}
           <div class="alert alert-danger fade in text-center">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            {{ message }}
          </div>
        {% endif %}
      {% endfor %}
  {% endif %}
  <div class="cont">
   <header>
    <h1 class="head">Student Registration</h1>
  </header>       
  <div  class="form" >
        <form id="contactform" action="{% url 'studentRegistration' %}" enctype="multipart/form-data" method="post">{% csrf_token %}
           <p class="contact"><label for="{{form.name.id_for_label}}">Name*</label></p> 
           <input id="id_name" maxlength="200" name="name" type="text" required="" />
           <p class="contact"><label for="{{form.admissionNumber.id_for_label}}">Admission No.*</label></p> 
           <input id="id_admissionNumber" maxlength="200" name="admissionNumber" type="text" required="" />

           <p class="contact"><label for="{{form.typ.id_for_label}}">Type*</label></p> 
           {{form.typ}}

           <p class="hide"><label for="{{form.clss.id_for_label}}"></label> 
           {{form.clss}}</p>

           <p class="contact"><label for="{{form.course.id_for_label}}">Course*</label></p> 
           {{form.course}}
           <p class="contact"><label for="{{form.branch.id_for_label}}">Branch*</label></p> 
           {{form.branch}}

          <fieldset><label for="{{form.validtill.id_for_label}}">Valid Till*&nbsp  &nbsp &nbsp &nbsp&nbsp</label>
          {{form.validtill}}</fieldset>

          <fieldset><label for="{{form.dateofbirth.id_for_label}}">Date of Birth*&nbsp </label>
          {{form.dateofbirth}}</fieldset>

          <p class="contact"><label for="{{form.bloodgroup.id_for_label}}">Blood Group</label></p> 
          {{form.bloodgroup}}

          <p class="contact"><label for="{{form.address.id_for_label}}">Address*</label></p> 
          <input id="id_address" maxlength="200" name="address" type="text" required="" />

          <p class="contact"><label for="{{form.contact1.id_for_label}}">Contact No.1*</label></p> 
          <input id="id_contact1" maxlength="10" name="contact1" type="text" required="" /> <br>

          <p class="contact"><label for="{{form.contact2.id_for_label}}">Contact No.2</label></p> 
          {{form.contact2}} <br>

          <p class="contact"><label for="{{form.photo.id_for_label}}">Photo</label></p> 
          {{form.photo}}<br>

          <input class="buttom" name="submit" id="submit" value="Register" type="submit"> 
          <input class="buttom report" name="submit" id="submit" value="Generate Report" type="submit" onClick="fun()"> 
          <a href="/studentRegistration/"><button class="buttom btn btn-primary new" type="button">New</button></a>
        </form> 
     
  </div>      
</div>
<script src="/static/js/jquery.js"></script>
<script src="/static/js/bootstrap.min.js"></script>
<script type="text/javascript">
  function fun(){
    var action = {% url 'report' %}
    $("#contactform").attr("action", action);

  }
</script>
</body>

</html>

{% endblock %}